### ISSUE TITLE
Send image to journal

### ISSUE THREAD

**Issue by handuozh** [akhater/Lupin#1]
I think it is also possible to send image to either asset/ folder under your note or github CDN of URL, via "bot.send_photo" command. Look forward to that function!

**Comment by akhater** [comment]
Hello there

this is definitely very high on my priority list. it is one of the main reasons I started Lupin

However I have some challenges to solve first since

- upload to the assets folder and I have no way to "hotlink" it in the journal
- upload to a CDN I need to find a way to support all the CDNs out-there 

I am, for now, waiting for the relative links to work inside LogSeq & I will fire it

**Comment by akhater** [comment]
coming soon

**Comment by akhater** [comment]
available with https://github.com/akhater/Lupin/commit/e738742b5a1d4a98483142adffef86c48799506d
support for both Github storage (view only on desktop app) & google firebase storage (the one I use)

**Comment by handuozh** [comment]
Wow! I just tried the github storage and it works like a charm~~
Thank you for your hard work!
So just curious, I just need to set that "assetsDestination=Firebase" and then set the BucketName to make firebase storage work, right?

**Comment by akhater** [comment]
> Wow! I just tried the github storage and it works like a charm~~
> Thank you for your hard work!
> So just curious, I just need to set that "assetsDestination=Firebase" and then set the BucketName to make firebase storage work, right?

yes sir indeed ...
so far anonymous upload shld be enabled on your firebase storage, viewing can be restricted
these are my firebase storage rules
![image](https://user-images.githubusercontent.com/22518020/107364896-b8c5f180-6ae4-11eb-8cd8-c631f48a6ddb.png)
